stages:
  load_data:
    cmd: python src/load_save.py --config=config/config.yaml
    deps:
      - src/load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - artifacts/raw_local_dir/data.csv
  stage2_train_test_split:
    cmd: python src/stage2_train_test_split.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
      - params.yaml
    params:
      - base.random_state
      - base.test_size
    outs:
      - artifacts/split_data_dir/train.csv
      - artifacts/split_data_dir/test.csv
